config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'atms#index', as: :home
  resources :atms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atm.rb
class Atm < ApplicationRecord
  has_one :location, dependent: :destroy

  validate :location_fields, if: :location_invalid?

  DISTANCE_THRESHOLD = 25000.freeze
  RESULT_LIMIT = 5.freeze

  def self.nearest(lat, long, distance_threshold = DISTANCE_THRESHOLD)
    Rails.cache.fetch([self.class.name, lat, long], expires_in: 1.hour) {
      find_by_sql("
        SELECT atms.*, locs.distance
        FROM (
          SELECT *, ( 6371 * acos( cos( radians(#{lat}) ) * cos( radians( latitude ) )
                           * cos( radians( longitude ) - radians(#{long}) )
                           + sin( radians(#{lat}) ) * sin ( radians ( latitude ) ) )
        ) AS distance FROM locations) as locs
        INNER JOIN atms on locs.atm_id = atms.id
        WHERE distance < #{distance_threshold}
        ORDER BY distance
        LIMIT #{RESULT_LIMIT};
      ")
    }
  end

  private

  def location_invalid?
    !location.valid?
  end

  def location_fields
    location.errors.messages.each do |field, msgs|
      errors.add(I18n.t("activerecord.attributes.location.#{field}"), msgs.join(', '))
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :atm

  validates :latitude, :longitude, presence: true
  validates :latitude,  numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/atms_controller.rb
class AtmsController < ApplicationController
  before_action :set_atm_filter, only: :index

  def new
    @atm = Atm.new
  end

  def index
    @results = @atm_filter.perform if @atm_filter.valid?
  end

  def create
    @atm = Atm.new(atm_params)
    @atm.build_location(location_params)

    if @atm.save
      redirect_to home_path, notice: t('activerecord.notices.atm_cteated')
    else
      render :new
    end
  end

  private

  def atm_params
    params.require(:atm).permit(:id, :address)
  end

  def location_params
    params.require(:atm).require(:location).permit(:latitude, :longitude)
  end

  def filter_params
    return {} unless params[:filter]
    params.require(:filter).permit(:latitude, :longitude)
  end

  def set_atm_filter
    @atm_filter ||= AtmFilter.new(filter_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page_name
    I18n.t("#{controller_name}.#{action_name}.page_name")
  end
end

app/helpers/atms_helper.rb
module AtmsHelper
  def rounded_value(value)
    value.round(2)
  end

  def search_results_header
    I18n.t(
      'activerecord.attributes.atm.search_results',
      distance: Atm::DISTANCE_THRESHOLD,
      qty: @results.size
    )
  end
end

app/views/atms/_filter.html.slim
= render partial: 'shared/flash_messages', locals: { resource: @atm_filter }
= form_for @atm_filter, as: :filter, url: atms_path, method: :get,
  html: { class: 'form-inline' } do |f|
  .form-group
    label for="filter_latitude" = AtmFilter.human_attribute_name(:latitude)
    | &nbsp
    = f.text_field :latitude, class: 'form-control'
  | &nbsp
  .form-group
    label for="filter_longitude"  = AtmFilter.human_attribute_name(:longitude)
    | &nbsp
    = f.text_field :longitude, class: 'form-control'
  = f.submit t('buttons.search'), class: 'btn btn-default'

app/views/atms/_form.html.slim
= form_for @atm, html: { class: 'form form-horizontal' } do |f|
  .form-group
    label.col-sm-2.control-label for="atm_address"
      = Atm.human_attribute_name(:address)
    .col-sm-6
      = f.text_field :address, class: 'form-control'
  = f.fields_for :location, f.object.location || f.object.build_location do |loc|
    .form-group
      label.col-sm-2.control-label for="atm_location_latitude"
        = Location.human_attribute_name(:latitude)
      .col-sm-6
        = loc.text_field :latitude, class: 'form-control'
    .form-group
      label.col-sm-2.control-label for="atm_location_longitude"
        = Location.human_attribute_name(:longitude)
      .col-sm-6
        = loc.text_field :longitude, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-6
      = f.submit t('buttons.save'), class: 'btn btn-default'

app/views/atms/_result_table.html.slim
h3 = search_results_header

table.table.table-condensed.text-center
  thead
    tr
      th.text-center #
      th.text-center = t('activemodel.attributes.atm_filter.atm')
      th.text-center = t('activemodel.attributes.atm_filter.address')
      th.text-center = t('activemodel.attributes.atm_filter.distance')
  tbody
    - @results.each.with_index(1) do |record, index|
      tr
        td.text-center = index
        td.text-center = record.id
        td.text-center = record.address
        td.text-center = rounded_value(record.distance)

app/views/atms/index.html.slim
= render partial: 'shared/notice'

p
  = link_to t('buttons.new'), new_atm_path

.atm-filter.text-center
  = render 'filter'
  .result-table
  - if @results.present?
    = render 'result_table'
  - else
    h3 = t('activerecord.attributes.atm.no_records') if params[:filter]

app/views/atms/new.html.slim
= link_to t('buttons.back'), home_path

- if @atm.errors.any?
  = render partial: 'shared/flash_messages', locals: { resource: @atm }
= render 'form'

app/views/layouts/application.html.slim
doctype html
html
  head
    title nearest_atm
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" rel="stylesheet"

  body
    .container
      h3 = current_page_name
      = yield

app/views/shared/_flash_messages.html.slim
- if resource.errors.any?
  .alert.alert-danger.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
    p = t('activerecord.errors.header_title')
    - resource.errors.messages.each do |attribute, messages|
      - messages.each do |message|
        = "#{attribute} #{message}"
        br

app/views/shared/_notice.html.slim
-flash.each do |type, message|
  .alert.alert-success.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
    .text-center
      = message